# Generated by Django 4.2.3 on 2023-08-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestation',
            name='Mnf_document',
            field=models.FileField(upload_to='Documents/Manifestation/'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='Mnf_logo',
            field=models.ImageField(blank=True, null=True, upload_to='Images/Logos/'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='Rfc_document',
            field=models.FileField(upload_to='Documents/Reference'),
        ),
    ]
