# Generated by Django 4.2.3 on 2023-08-13 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0002_alter_manifestation_mnf_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestation',
            name='Mnf_date',
        ),
        migrations.AddField(
            model_name='manifestation',
            name='Mnf_moment',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
