# Generated by Django 4.2.3 on 2023-08-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0003_remove_manifestation_mnf_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation3',
            name='Ptn3_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
