# Generated by Django 4.2.3 on 2023-08-08 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation3',
            fields=[
                ('Alc3_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Appel_a_Manifestation',
            fields=[
                ('Ami_numero', models.CharField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(8)])),
                ('Ami_titre', models.CharField(max_length=96)),
                ('Ami_description', models.TextField()),
                ('Ami_dateDebut', models.DateField()),
                ('Ami_dateFin', models.DateField()),
                ('Ami_delaiValidite', models.IntegerField()),
                ('Ami_document', models.FileField(upload_to='media/Documents/AppelaManifestation/')),
                ('Ami_coordonnees', models.CharField(max_length=160)),
                ('Ami_statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('EN_ATTENTE', 'En attente'), ('TERMINE', 'Terminé')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Appel_d_Offre',
            fields=[
                ('Apl_numero', models.CharField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(8)])),
                ('Apl_titre', models.CharField(max_length=96)),
                ('Apl_description', models.TextField()),
                ('Apl_exigences', models.TextField()),
                ('Apl_dateDebut', models.DateField()),
                ('Apl_dateFin', models.DateField()),
                ('Apl_document', models.FileField(upload_to='media/Documents/AppeldOffre/')),
                ('Apl_coordonnees', models.CharField(max_length=160)),
                ('Apl_budget', models.FloatField()),
                ('Apl_statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('EN_ATTENTE', 'En attente'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('Cnd_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Critere',
            fields=[
                ('Crt_id', models.AutoField(primary_key=True, serialize=False)),
                ('Crt_intitule', models.CharField(max_length=32)),
                ('Crt_ponderation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prestation1',
            fields=[
                ('Ptn1_id', models.AutoField(primary_key=True, serialize=False)),
                ('Ptn1_description', models.TextField()),
                ('Ptn1_delai', models.IntegerField()),
                ('Ptn1_quantite', models.IntegerField()),
                ('Ptn1_budget', models.FloatField()),
            ],
        ),
    ]
