# Generated by Django 4.2.3 on 2023-07-31 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appels', '0001_initial'),
        ('entreprises', '0001_initial'),
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation1',
            name='Ctg_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprises.categorie'),
        ),
        migrations.AddField(
            model_name='condition',
            name='Apl_numero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appels.appel_d_offre'),
        ),
        migrations.AddField(
            model_name='condition',
            name='Crt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appels.critere'),
        ),
        migrations.AddField(
            model_name='appel_d_offre',
            name='Apl_criteres',
            field=models.ManyToManyField(through='appels.Condition', to='appels.critere'),
        ),
        migrations.AddField(
            model_name='appel_d_offre',
            name='Apl_prestations',
            field=models.ManyToManyField(through='appels.Allocation3', to='appels.prestation1'),
        ),
        migrations.AddField(
            model_name='appel_d_offre',
            name='Pjt_numero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.projet_d_approvisionnement'),
        ),
        migrations.AddField(
            model_name='appel_a_manifestation',
            name='Ami_Entreprises',
            field=models.ManyToManyField(null=True, through='entreprises.Manifestation', to='entreprises.entreprise'),
        ),
        migrations.AddField(
            model_name='allocation3',
            name='Apl_numero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appels.appel_d_offre'),
        ),
        migrations.AddField(
            model_name='allocation3',
            name='Ptn1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appels.prestation1'),
        ),
        migrations.AddConstraint(
            model_name='condition',
            constraint=models.UniqueConstraint(fields=('Apl_numero', 'Crt_id'), name='condition_pk'),
        ),
        migrations.AddConstraint(
            model_name='allocation3',
            constraint=models.UniqueConstraint(fields=('Apl_numero', 'Ptn1_id'), name='allocation3_pk'),
        ),
    ]
