# Generated by Django 4.2.3 on 2023-08-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appel_a_manifestation',
            name='Ami_document',
            field=models.ImageField(upload_to='Documents/AppelaManifestation/'),
        ),
        migrations.AlterField(
            model_name='appel_d_offre',
            name='Apl_document',
            field=models.ImageField(upload_to='Documents/AppeldOffre/'),
        ),
    ]
