# Generated by Django 4.2.3 on 2023-08-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0004_alter_appel_d_offre_apl_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appel_d_offre',
            name='Apl_document',
            field=models.ImageField(upload_to='Documents/AppeldOffre/'),
        ),
    ]
