# Generated by Django 4.2.3 on 2023-07-31 01:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appels', '0001_initial'),
        ('entreprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('Cnt_numero', models.CharField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(8)])),
                ('Cnt_type', models.CharField(max_length=48)),
                ('Cnt_occurence', models.CharField(choices=[('RENOUVELABLE', 'Renouvelable'), ('NON_RENOUVELABLE', 'Non renouvelable')], max_length=20)),
                ('Cnt_dateDebut', models.DateField()),
                ('Cnt_modeResiliation', models.CharField(max_length=96)),
                ('Cnt_statut', models.CharField(choices=[('EN_VALIDATION', 'En validation'), ('VALIDE', 'Validé'), ('INVALIDE', 'Invalidé'), ('EN_COURS', 'En cours'), ('RESILIE', 'Résilié'), ('ACHEVE', 'Achevé')], default='EN_EVALUATION', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation1',
            fields=[
                ('Evl1_id', models.AutoField(primary_key=True, serialize=False)),
                ('Evl1_note', models.IntegerField(null=True)),
                ('Cnd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appels.condition')),
            ],
        ),
        migrations.CreateModel(
            name='Indicateur',
            fields=[
                ('Ind_id', models.AutoField(primary_key=True, serialize=False)),
                ('Ind_intitule', models.CharField(max_length=32)),
                ('Ind_ponderation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('Vrs_id', models.AutoField(primary_key=True, serialize=False)),
                ('Vrs_description', models.TextField()),
                ('Vrs_momentSignature', models.DateTimeField(blank=True, null=True)),
                ('Vrs_dateFin', models.DateField()),
                ('Vrs_document', models.FileField(upload_to='Documents/Contrat')),
                ('Vrs_modePaiement', models.CharField(max_length=96)),
                ('Vrs_statut', models.CharField(choices=[('EN_VALIDATION', 'En validation'), ('INVALIDE', 'Invalidé'), ('VALIDE', 'Validé')], default='EN_EVALUATION', max_length=20)),
                ('Cnt_numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reponses.contrat')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('Pmt_numero', models.CharField(max_length=100, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(8)])),
                ('Pmt_mode', models.CharField(max_length=24)),
                ('Pmt_description', models.TextField()),
                ('Pmt_montant', models.FloatField()),
                ('Pmt_date', models.DateField()),
                ('Pmt_document', models.FileField(upload_to='Documents/Paiement')),
                ('Pmt_statut', models.CharField(choices=[('EN_VALIDATION', 'En validation'), ('INVALIDE', 'Invalidé'), ('VALIDE', 'Validé')], default='EN_EVALUATION', max_length=20)),
                ('Cnt_numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reponses.contrat')),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('Ofr_numero', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('Ofr_description', models.TextField()),
                ('Ofr_specifications', models.TextField()),
                ('Ofr_montant', models.FloatField()),
                ('Ofr_date', models.DateField(auto_now_add=True)),
                ('Ofr_evaluation', models.FloatField(null=True)),
                ('Ofr_document', models.FileField(upload_to='Documents/Offre')),
                ('Ofr_statut', models.CharField(choices=[('EN_EVALUATION', 'En évaluation'), ('ACCEPTEE', 'Acceptée'), ('REJETEE', 'Rejetée')], default='EN_EVALUATION', max_length=24)),
                ('Apl_numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appels.appel_d_offre')),
                ('Ent_numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprises.entreprise')),
                ('Ofr_conditions', models.ManyToManyField(through='reponses.Evaluation1', to='appels.condition')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation2',
            fields=[
                ('Evl2_id', models.AutoField(primary_key=True, serialize=False)),
                ('Evl2_note', models.IntegerField(null=True)),
                ('Cnt_numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reponses.contrat')),
                ('Ind_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reponses.indicateur')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation1',
            name='Ofr_numero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reponses.offre'),
        ),
        migrations.CreateModel(
            name='Etape2',
            fields=[
                ('Etp2_id', models.AutoField(primary_key=True, serialize=False)),
                ('Etp2_titre', models.CharField(max_length=48)),
                ('Etp2_description', models.TextField()),
                ('Etp2_objectifs', models.TextField()),
                ('Etp2_datePrevue', models.DateField()),
                ('Etp2_dateExecution', models.DateField(blank=True, null=True)),
                ('Etp2_statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('EN_ATTENTE', 'En attente'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], max_length=20)),
                ('Cnt_numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reponses.contrat')),
            ],
        ),
        migrations.AddField(
            model_name='contrat',
            name='Cnt_indicateurs',
            field=models.ManyToManyField(through='reponses.Evaluation2', to='reponses.indicateur'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='Ofr_numero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reponses.offre'),
        ),
        migrations.AddConstraint(
            model_name='evaluation2',
            constraint=models.UniqueConstraint(fields=('Cnt_numero', 'Ind_id'), name='evaluation2_pk'),
        ),
        migrations.AddConstraint(
            model_name='evaluation1',
            constraint=models.UniqueConstraint(fields=('Cnd_id', 'Ofr_numero'), name='evaluation1_pk'),
        ),
    ]
