# Generated by Django 4.2.3 on 2023-08-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reponses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='Ofr_document',
            field=models.FileField(upload_to='Documents/Offre'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='Pmt_document',
            field=models.FileField(upload_to='Documents/Paiement'),
        ),
        migrations.AlterField(
            model_name='version',
            name='Vrs_document',
            field=models.FileField(upload_to='Documents/Contrat'),
        ),
    ]
