# Generated by Django 4.2.3 on 2023-08-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reponses', '0006_alter_paiement_pmt_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='Cnt_statut',
            field=models.CharField(choices=[('EN_VALIDATION', 'En validation'), ('VALIDE', 'Validé'), ('INVALIDE', 'Invalidé'), ('EN_COURS', 'En cours'), ('RESILIE', 'Résilié'), ('ACHEVE', 'Achevé')], default='EN_VALIDATION', max_length=20),
        ),
    ]
