# Generated by Django 4.2.3 on 2023-07-31 01:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet_d_Approvisionnement',
            fields=[
                ('Pjt_numero', models.CharField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(8)])),
                ('Pjt_titre', models.CharField(max_length=96)),
                ('Pjt_description', models.TextField()),
                ('Pjt_dateDebut', models.DateField()),
                ('Pjt_dateFin', models.DateField()),
                ('Pjt_objectifs', models.TextField()),
                ('Pjt_document', models.FileField(upload_to="Documents/Projet d'Approvisionnement")),
                ('Pjt_budget', models.FloatField()),
                ('Pjt_statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('EN_ATTENTE', 'En attente'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Etape1',
            fields=[
                ('Etp1_id', models.AutoField(primary_key=True, serialize=False)),
                ('Etp1_titre', models.CharField(max_length=48)),
                ('Etp1_description', models.TextField()),
                ('Etp1_objectifs', models.TextField()),
                ('Etp1_dateDebut', models.DateField()),
                ('Etp1_dateFin', models.DateField()),
                ('Etp1_budget', models.FloatField()),
                ('Etp1_statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('EN_ATTENTE', 'En attente'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], max_length=20)),
                ('Pjt_numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.projet_d_approvisionnement')),
            ],
        ),
    ]
