# Generated by Django 4.2.3 on 2023-08-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet_d_approvisionnement',
            name='Pjt_document',
            field=models.ImageField(blank=True, null=True, upload_to="Documents/Projet d'Approvisionnement"),
        ),
    ]
